{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fingerprint-ingestor.fullname" . }}
  labels:
    {{- include "fingerprint-ingestor.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "fingerprint-ingestor.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval | default "30s" }}
    path: {{ .Values.serviceMonitor.path | default "/metrics" }}
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
{{- end }}
