apiVersion: v2
name: advertiser-api
description: ACRaaS advertiser API service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - acraas
  - api
  - advertiser
home: https://github.com/synora/acraas
sources:
  - https://github.com/synora/acraas
maintainers:
  - name: ACRaaS Team
    email: platform@synora.io
